"""Golden-file tests for write_start_script and render_compose.

These verify that the per-model launch scripts and docker-compose output
the TUI generates contain the expected structure and correctness-critical
flags (--jinja, kv cache type, flash-attn, etc.).
"""
import os
import stat
from pathlib import Path

import pytest


LAUNCH_FLAGS = [
    "--jinja",
    "--ctx-size", "98304",
    "-ngl", "999",
    "--parallel", "1",
    "--flash-attn", "on",
    "--cache-type-k", "q4_0",
    "--cache-type-v", "q4_0",
]

LAUNCH_FLAGS_CPU_MOE = LAUNCH_FLAGS + ["--cpu-moe"]


@pytest.fixture
def scripts_tmp(tmp_path, monkeypatch, tui):
    """Scratch SCRIPTS_DIR so tests don't write into ~/.relay."""
    monkeypatch.setattr(tui, "SCRIPTS_DIR", tmp_path)
    return tmp_path


def _no_companion(*args):
    return None


def test_basic_script_structure(scripts_tmp, monkeypatch, tui):
    """Generated script has shebang, cd, exec, model, host/port, flags, '$@'."""
    monkeypatch.setattr(tui, "companion_for", _no_companion)
    monkeypatch.setattr(tui, "IS_MAC", True)  # return host path, not container path

    out = tui.write_start_script(
        "my-model", Path("/m/models/model.gguf"),
        Path("/m/models"), Path("/opt/llama.cpp/llama-server"),
        Path("/opt/llama.cpp"), 8081, LAUNCH_FLAGS)

    assert out.endswith("start-my-model.sh")
    script_path = scripts_tmp / "start-my-model.sh"
    assert script_path.exists()
    content = script_path.read_text()

    assert "#!/usr/bin/env bash" in content
    assert "# relay model: my-model  (generated by relay setup)" in content
    assert 'cd "/opt/llama.cpp"' in content
    assert 'exec "/opt/llama.cpp/llama-server"' in content
    assert '--model "/m/models/model.gguf"' in content
    assert '--host 127.0.0.1 --port "${LLAMA_PORT:-8081}"' in content
    assert "--jinja" in content
    assert "--ctx-size 98304" in content
    assert "-ngl 999" in content
    assert "--cache-type-k q4_0" in content
    assert "--cache-type-v q4_0" in content
    assert '"$@"' in content
    # executable
    assert script_path.stat().st_mode & stat.S_IXUSR


def test_script_with_mmproj(scripts_tmp, monkeypatch, tui):
    """When a companion mmproj is found, --mmproj is added."""
    mmproj = Path("/m/models/mmproj-model.gguf")
    monkeypatch.setattr(tui, "companion_for", lambda gguf, kind: mmproj if kind == "mmproj" else None)
    monkeypatch.setattr(tui, "IS_MAC", True)

    tui.write_start_script(
        "vision-model", Path("/m/models/model.gguf"),
        Path("/m/models"), Path("/opt/llama.cpp/llama-server"),
        Path("/opt/llama.cpp"), 8082, LAUNCH_FLAGS)

    content = (scripts_tmp / "start-vision-model.sh").read_text()
    assert '--mmproj "/m/models/mmproj-model.gguf"' in content


def test_script_with_draft(scripts_tmp, monkeypatch, tui):
    """When a companion draft is found, --model-draft is added."""
    draft = Path("/m/models/mtp-model.gguf")
    monkeypatch.setattr(tui, "companion_for", lambda gguf, kind: draft if kind == "draft" else None)
    monkeypatch.setattr(tui, "IS_MAC", True)

    tui.write_start_script(
        "fast-model", Path("/m/models/model.gguf"),
        Path("/m/models"), Path("/opt/llama.cpp/llama-server"),
        Path("/opt/llama.cpp"), 8083, LAUNCH_FLAGS)

    content = (scripts_tmp / "start-fast-model.sh").read_text()
    assert '--model-draft "/m/models/mtp-model.gguf"' in content


def test_script_with_cpu_moe(scripts_tmp, monkeypatch, tui):
    """When launch_flags include --cpu-moe, it appears in the script."""
    monkeypatch.setattr(tui, "companion_for", _no_companion)
    monkeypatch.setattr(tui, "IS_MAC", True)

    tui.write_start_script(
        "big-model", Path("/m/models/model.gguf"),
        Path("/m/models"), Path("/opt/llama.cpp/llama-server"),
        Path("/opt/llama.cpp"), 8084, LAUNCH_FLAGS_CPU_MOE)

    content = (scripts_tmp / "start-big-model.sh").read_text()
    assert "--cpu-moe" in content


def test_linux_returns_container_path(scripts_tmp, monkeypatch, tui):
    """On Linux (IS_MAC=False), the path is inside the container."""
    monkeypatch.setattr(tui, "companion_for", _no_companion)
    monkeypatch.setattr(tui, "IS_MAC", False)

    out = tui.write_start_script(
        "container-model", Path("/m/models/model.gguf"),
        Path("/m/models"), Path("/opt/llama.cpp/llama-server"),
        Path("/opt/llama.cpp"), 8085, LAUNCH_FLAGS)

    assert out == "/relay/start-scripts/start-container-model.sh"
    local_path = scripts_tmp / "start-container-model.sh"
    assert local_path.exists()


def test_render_compose_structure(monkeypatch, tui):
    """render_compose produces valid docker-compose with expected structure."""
    models_dir = Path("/m/models")
    llama_root = Path("/opt/llama.cpp")
    compose = tui.render_compose(models_dir, llama_root)

    assert "services:" in compose
    assert "relay:" in compose
    assert "image: relay-gateway:local" in compose
    assert "container_name: relay" in compose
    assert "restart: unless-stopped" in compose
    assert "network_mode: host" in compose
    assert "pid: host" in compose
    assert "env_file:" in compose
    assert "- .env" in compose
    assert "volumes:" in compose
    assert f"{models_dir}:{models_dir}:ro" in compose
    assert f"{llama_root}:{llama_root}:ro" in compose
    assert "/relay/start-scripts:ro" in compose
